---
title: "make_k9_cluster_palette_uniformluminance"
format: html
author: Bernie Mulvey
date: 04-05-25
---

```{r}
knitr::opts_knit$set(root.dir = here::here())
library(Polychrome)
library(data.table)
```

```{r}
## load the cell type annotations to name colors by
anno <- fread("processed-data/08_validitycheck_25hdg75svg_louv1/10-25hdg75svg_louv1_annots.txt")

## get some initial colors with cerulean as the color for LC of course
## so that expression plots in escheR where spot outlining for cluster and fill for expression do not convey false differences in dark/light across cluster colors, set luminance to a tiny range (polychrome won't let us use a single value). (and avoid black-white-gray because for the expression plotting a grayscale works best.)
set.seed(9001)
pal <- Polychrome::createPalette(seedcolors = "#007ba7", N = 9,M=2500000,range = c(75:76)) # 007ba7 : cerulean. obviously; color samplespace 50x default
# colors 1,3,4,6,7,8 are fine. 2/5 are no good (orange/brown, bad for NM connotations here).
# use the first set of colors as seeds to get 20 more minimally related colors to pick from
set.seed(9009)
pal2 <- Polychrome::createPalette(seedcolors = pal, N = 29,M=2500000,range=c(75:76))
pal2 <- c(pal,pal2[10:29]) # first 9 colors are basically the seed colors but oddly like just slightly different values, so replace those slots with the actual seed colors
# peek
swatch(pal2)
## alright, we want 1,4, 5, 7, 10, 11, 14 here (greens for SERT ACHE, cerulean for LC, purples for oligos, red for vascular, and 2 yellows for astros (We're not getting any good yellows here with desired luminance.)
pal3 <- pal2[c(1,4,5,7,10,11,14)]
## use a manual color picker to find something luminance matched but distinctive from 21 and 7 which is sorta yellow tinged
## alright, we want 1, 5, 7, 9, 10, 11, 14 here (greens for SERT ACHE, cerulean for LC, purples for oligos, red for vascular, and 2 yellows for astros (We're not getting any good yellows here with desired luminance.)
## for our two yellows, use #e6f391 #f3df91 which are luminance matched.
pal3 <- c(pal3,"#e6f391","#f3df91")
swatch(pal3)

## assign names to color slots
## print annots for ease of this next bit
anno$anno
# make the more blueish green ACHE..npeps since this is the cluster that had a lot of indicators of minority LC-related content and kinda trended behind LC on proportions of spots expressing various genes of interest
# make oligo_3 (the APLP1 marked one) the stark purple, since that's the real interesting oligo cluster here
# names(pal3) <- c("LC.1","ACHE_SERT_SLC17A6_Npeps","Oligo_3","ACHE_SERT_SLC17A6_ADCYAP1","Oligo_1","Oligo_2","Vascular","Astro_2_APOE","Astro_1")
names(pal3) <- c("LC","ACHE_SERT_LC_WM","Oligo_Complex","ACHE_SERT_Npep","Oligo_Astro","Oligo","Vascular","Astro_Oligo","Astro")
swatch(pal3)
saveRDS(pal3,"plots/cluster_palette_narrowluminance.RDS")

### make a second one where the astros get the more vibrant colors from above (Oligo_1 and Oligo_3), oligos get the duller/greiges. need one more color for the oligos in this setup
pal4 <- pal3[c(1:5,7:9)]
names(pal4)[3] <- "Astro"
names(pal4)[5] <- "Astro_Oligo"
names(pal4)[7] <- "Oligo"
names(pal4)[8] <- "Oligo_Astro"
swatch(pal4)

## make a big old palette to draw a greige from, seeding with the non-yellow/beiges
set.seed(42)
findgreige <- Polychrome::createPalette(seedcolors = pal4[1:6], N = 50,M=2500000,range = c(74:77)) # 007ba7 : cerulean. obviously; color samplespace 50x default
swatch(findgreige)

pal4 <- c(pal4,findgreige[20])
names(pal4)[7] <- "Oligo_Complex"
names(pal4)[9] <- "Oligo"
pal4 <- c(pal4[1:6],pal4[9],pal4[8],pal4[7])
## reorder so clusters are by type for swatching
pal4 <- pal4[c(1,2,4,3,5,6:9)]
swatch(pal4)

saveRDS(pal4,"plots/cluster_palette_narrowluminance_v2.RDS")
## 4 clusters are being excluded from DE analyses, so also plot how this looks with only those 5 colors considered
pal5 <- pal4[c(1,2,3,4,8)]
swatch(pal5)
```
