---
title: "10-Unique_DEGs_per_cluster"
author: "Bernie Mulvey"
date: "2025-07-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(edgeR)
library(limma)
# library(SpatialFeatureExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

```{r}
deres <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/02b-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAnces_LabAncesE4E2_noMixClusts_YRIcontAndCat_JUL2025.RDS")

deres <- lapply(deres,FUN=function(d){
    ret <- lapply(d,function(x){
        y <- x[[6]] # slot with DE tables
        return(y)
    })
})

## for each comparison within an ancestry coding scheme, get the genes unique to one cluster

### split the allele comparisons into separate groups for this
i<-1
for (i in c(1:length(deres))){
    deres[[i]]$ApoAllelesLabel$E2hom_vs_anyE4 <- deres[[i]]$ApoAllelesLabel[seq(1,30,by=6)]
    deres[[i]]$ApoAllelesLabel$E2het_vs_anyE4 <- deres[[i]]$ApoAllelesLabel[seq(2,30,by=6)]
    deres[[i]]$ApoAllelesLabel$E4hom_vs_anyE2 <- deres[[i]]$ApoAllelesLabel[seq(3,30,by=6)]
    deres[[i]]$ApoAllelesLabel$E4het_vs_anyE2 <- deres[[i]]$ApoAllelesLabel[seq(4,30,by=6)]
    deres[[i]]$ApoAllelesLabel$E4hom_vs_E4het <- deres[[i]]$ApoAllelesLabel[seq(5,30,by=6)]
    deres[[i]]$ApoAllelesLabel$E4hom_vs_others <- deres[[i]]$ApoAllelesLabel[seq(6,30,by=6)]
    deres[[i]]$ApoAllelesLabel <- deres[[i]]$ApoAllelesLabel[31:36]
}

## get unique genes for all the other contrasts
uniqs <- lapply(deres,function(d){
    uniqsout <- lapply(d[names(d)!="ApoAllelesLabel"],function(z){
            u <- rbindlist(z,idcol="clustertest")
            singg <- u[adj.P.Val<0.05,.N,by="gene_name"][N==1,gene_name]
            o <- u[gene_name %in% singg&adj.P.Val<0.05]
            return(o)
        })
    return(uniqsout)
})

## get the unique genes for each ApoAllelesLabel contrast
apouniqs <- lapply(deres,function(d){
    uniqsout <- lapply(d$ApoAllelesLabel,function(z){
            u <- rbindlist(z,idcol="clustertest")
            singg <- u[adj.P.Val<0.05,.N,by="gene_name"][N==1,gene_name]
            o <- u[gene_name %in% singg&adj.P.Val<0.05]
            return(o)
        })
    return(uniqsout)
})

uniqs$cat_ances <- c(uniqs$cat_ances,apouniqs$cat_ances)
uniqs$cont_ances <- c(uniqs$cont_ances,apouniqs$cont_ances)


saveRDS(uniqs,"processed-data/12_DEanalyses_removedsampsAndFinalNMseg/10-LabSex_LabE4vE2_LabSingleGeno_LabPredomAnces_SingleClusterDEGswithinTest.RDS")
```
