---
title: "Fig4-Sex DE"
author: "Bernie Mulvey"
date: "2025-05-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(gridExtra)
library(ggrastr)
library(ggrepel)
library(SpatialExperiment)
library(escheR)
library(scater)
library(jaffelab) # cleaningY
library(SpatialExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 8,color = "#000000"), axis.title.x = element_text(size = 9,color = "#000000"), axis.text.y = element_text(size = 8,color = "#000000"), axis.title.y = element_text(size =9,color = "#000000"), plot.title = element_markdown(size = 10,hjust=0.5,color = "#000000"), strip.text = element_text(size=11), legend.text = element_text(size=7,color = "#000000"), legend.title = element_text(size=8,hjust=0.5,color = "#000000"),plot.title.position="plot",axis.ticks = element_line(linewidth=0.5),panel.grid.major = element_line(linewidth=0.5),panel.grid.minor=element_line(linewidth=0.25)))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```


### helper function to extract a legend and pipe back to a diff plot: from https://statisticsglobe.com/add-common-legend-to-combined-ggplot2-plots-in-r/#example-2-add-shared-legend-to-ggplot2-plots-using-gridextra-package 
```{r}
extract_legend <- function(my_ggp) {
    step1 <- ggplot_gtable(ggplot_build(my_ggp))
    step2 <- which(sapply(step1$grobs, function(x) x$name) == "guide-box")
    step3 <- step1$grobs[[step2]]
    return(step3)
}
```


Fig 3A/B/C: Volcanos (ACHE_SERT_LC_WM, LC, Astro)
```{r}
## load cluster palette
pal <- readRDS("plots/finalpal_somuchfornorainbows.RDS")
pal <- pal[c("LC","*ACHE*, *SERT*, LC, Oligo Mixed","Astro")]
names(pal)[2] <- "*ACHE*, *SERT*, LC,<br>Oligo Mixed"

detabs <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/02b-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAncesGrp_noMixClusts.RDS")
detabs <- detabs$SexByLabel$sexlabel_detabs

names(detabs) <- gsub(names(detabs),pattern="_Sex",replacement="")
names(detabs) <- gsub(names(detabs),pattern="_",replacement=" ")
names(detabs)[1] <- "*ACHE*, *SERT*, LC,<br>Oligo Mixed"

## identify genes to be labeled in plots
# LC TMC6 APOLD1 CHGB PRCP GSTT2B
# astro HSPB8 GASK1B NTSR2 DNAJB1
# achesertlc BAG3 PHYH CPNE6 LRRTM3
### LRRTM3: ncbi synopsis is brief and on point: "Acts upstream of or within positive regulation of amyloid-beta formation."

detabs$LC[,label:=""]
detabs$LC[gene_name %in% c("TMC6", "CHGB", "TCF20", "APOLD1", "PRCP", "GSTT2B"),label:=gene_name]

detabs$`*ACHE*, *SERT*, LC,<br>Oligo Mixed`[,label:=""]
detabs$`*ACHE*, *SERT*, LC,<br>Oligo Mixed`[gene_name %in% c("BAG3","PHYH","CPNE6","LRRTM3"),label:=gene_name]

detabs$Astro[,label:=""]
detabs$Astro[gene_name %in% c("HSPB8", "GASK1B", "NTSR2", "DNAJB1"),label:=gene_name]

## make a giant table of the results for all 3 clusters for legend purposes
pltdetabs <- detabs[c("LC","Astro","*ACHE*, *SERT*, LC,<br>Oligo Mixed")]
pltdetabs <- mapply(x=pltdetabs,n=names(pltdetabs),SIMPLIFY=FALSE,function(x,n){
    x[,clust:=n]
    return(x)
})

pltdetabs <- rbindlist(pltdetabs)

## get a legend
legplt <- ggplot(pltdetabs,aes(x=P.Value,y=logFC,col=clust))+
    geom_point()+
    labs(col="Visium<br>Cluster")+
    theme(legend.text=element_markdown(size=7,color="#000000"),
          legend.box.background=element_blank(),
          legend.title=element_markdown(size=8,color = "#000000"),
          legend.key.width=unit(0.083,"in"))

leg.plt <- extract_legend(legplt)
dev.off()
####

### make plots
fn <- c("LC","ACHE_SERT_LC_Oligo","Astro")

i<-1
for (i in c(1:3)){
    x <- names(pal)[i]
    n <- fn[i]
    
    p <- ggplot(pltdetabs[!(chr %in% c("chrX","chrY","chrMT"))&clust==x],aes(x=logFC,y=-log10(P.Value),col=clust)) +
        geom_point(size=0.9,stroke=0,alpha=0.7) +
        labs(x="log2FC (+: Male-up)",y="-log10 P-value") +
        geom_hline(yintercept = -log10(0.05), linetype="dashed", color="red",linewidth=0.5) +
        geom_text_repel(seed = 23942,aes(y = -log10(P.Value),
                x = logFC,
                label = ifelse(is.na(label), "", label)),
            min.segment.length = 0,
            size = 2,
            show.legend=FALSE,
            max.iter=100000,
            max.overlaps=10000,
            max.time=3,
            segment.size=0.4,
            force_pull = 0.65,
            fontface = "italic")+
        scale_color_manual(values=pal)+
        guides(color="none")

    
    if(n=="ACHE_SERT_LC_Oligo"){
        p <- p+theme(legend.text=element_markdown(size=7))
        w<-3
        
        p<-rasterize(p,layers="points",dpi=450,dev="cairo_png")
    
        pdf(paste0("plots/manuscript/Fig4/4ABC-SexDE_Volcano_",n,".pdf"),width=w,height=2,onefile=FALSE)
        do.call("grid.arrange",list(p,leg.plt,ncol=2,widths=c(2,1)))
        dev.off()
        
    } else {
        w <- 2
        
        p<-rasterize(p,layers="points",dpi=450,dev="cairo_png")
    
        pdf(paste0("plots/manuscript/Fig4/4ABC-SexDE_Volcano_",n,".pdf"),width=w,height=2,onefile=FALSE)
        print(p)
        dev.off()
    }
}
```

3D: GSEA: msigdb
```{r}
msigsex <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/03bi-MulticlusterDE_OneInterxnPerModel_dropMixClusts_GSEAmsigdb.RDS")

msigsex <- msigsex$LC_Sex[pathway %in% c("WP_CHOLESTEROL_METABOLISM", "YAO_TEMPORAL_RESPONSE_TO_PROGESTERONE_CLUSTER_1", "GOBP_MODULATION_OF_EXCITATORY_POSTSYNAPTIC_POTENTIAL", "BHAT_ESR1_TARGETS_VIA_AKT1_UP", "GOMF_TRANSFERASE_ACTIVITY_TRANSFERRING_PHOSPHORUS_CONTAINING_GROUPS", "REACTOME_AEROBIC_RESPIRATION_AND_RESPIRATORY_ELECTRON_TRANSPORT", "REACTOME_REGULATION_OF_EXPRESSION_OF_SLITS_AND_ROBOS", "REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES")]

## there's an entry per direction here so get the significant ones
msigsex <- msigsex[padj<0.05]

msigsex[pathway=="WP_CHOLESTEROL_METABOLISM",pathway:="Cholesterol metabolism"]
msigsex[pathway=="YAO_TEMPORAL_RESPONSE_TO_PROGESTERONE_CLUSTER_1",pathway:="Progesterone response"]
msigsex[pathway=="GOBP_MODULATION_OF_EXCITATORY_POSTSYNAPTIC_POTENTIAL",pathway:="Modulation of EPSP"]
msigsex[pathway=="BHAT_ESR1_TARGETS_VIA_AKT1_UP",pathway:="ESR1 upregulated via AKT1"]
msigsex[pathway=="GOMF_TRANSFERASE_ACTIVITY_TRANSFERRING_PHOSPHORUS_CONTAINING_GROUPS",pathway:="Transferase activity toward\nphosphorous-containing groups"]
msigsex[pathway=="REACTOME_AEROBIC_RESPIRATION_AND_RESPIRATORY_ELECTRON_TRANSPORT",pathway:="Aerobic respiration and ETC"]
msigsex[pathway=="REACTOME_REGULATION_OF_EXPRESSION_OF_SLITS_AND_ROBOS",pathway:="Regulation of Slits and Robos"]
msigsex[pathway=="REACTOME_METABOLISM_OF_AMINO_ACIDS_AND_DERIVATIVES",pathway:="AA and AA derivative metab."]

pdf("plots/manuscript/Fig4/4D-LCsexDE_msigdbGSEA.pdf",height=3,width=3.35)
ggplot(msigsex,aes(y=pathway,x=-log10(pval),color=NES,size=abs(NES)))+
    geom_point()+
    scale_color_gradient2(low="red",high="blue")+
    geom_vline(xintercept = -log10(0.05), linetype="dashed", color="black",linewidth=0.5) +
    scale_x_continuous(expand = c(0,2)) +
    #scale_y_discrete(expand = c(0,0)) +
    labs(x="-log10(p-value)",y="Msigdb Term",color="NES")+
    theme(axis.text.x=element_text(hjust=1,size=7,colour = "#000000"),
          axis.text.y=element_text(size=7,colour = "#000000"),
          axis.title.x=element_text(size=8,colour = "#000000"),
          axis.title.y=element_text(size=8,colour = "#000000", margin=margin(0,0,0,-0.02,unit="in")),
          legend.title=element_text(size=8,hjust=0.5,colour = "#000000"),
          legend.text=element_text(size=7,colour = "#000000"),
          legend.background=element_blank(),
          legend.margin=margin(0,-0.08,0,-0.1,unit="in"))+
    guides(size="none")
dev.off()
```

3E: pseudobulk plots of cholesterol metabolism genes
```{r}
pbulk <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/02b-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAncesGrp_noMixClusts.RDS")

gmat <- pbulk$SexByLabel$voomLFt$EList$E
# subset to LC
gmat <- gmat[,colnames(gmat) %in% grep(colnames(gmat),pattern="LC_V|^Astro_V",value=T)]
# make symbols
rownames(gmat) <- pbulk$SexByLabel$voomLFt$genes$gene_name

# get sample metadata in the same arrangement for LC pbulks
cd <- as.data.frame(pbulk$SexByLabel$voomLFt$targets)[colnames(gmat),]

# model matrix for "single cluster" (the label_sex thing doesn't work here)
modmat <- model.matrix(~0+label_sex+APOE+Age+YRI,data = cd)

testres <- jaffelab::cleaningY(gmat,modmat,4)

testres2 <- testres[c("HMGCS1","SC5D"),]
testres2 <- as.data.table(cbind(t(testres2),cd$label_sex,cd$brnum,cd$Sex,cd$label))
setnames(testres2,c((ncol(testres2)-3):ncol(testres2)),c("labsex","brnum","sex","label"))
testres2 <- as.data.table(cbind(testres2[,lapply(.SD,as.numeric),.SDcols=c(1:(ncol(testres2)-4))],testres2[,.(labsex,brnum,sex,label)]))

testres2 <- melt.data.table(testres2,id.vars=c("labsex","brnum","sex","label"))
testres2[,labsex:=gsub(labsex,pattern="_",replacement=" ")]
testres2[,variable:=paste0("*",variable,"*")]

sexpal <- c(M="lightgray",F="#FFFFFF")

pdf("plots/manuscript/Fig4/4E-Cholestgenes_astro_LC_pbulk.pdf",height=3,width=4)
ggplot(testres2,aes(x=labsex,y=value,color=label,fill=sex))+
    geom_boxplot(outliers = F,linewidth = 0.25)+
    geom_point(alpha=0.7,size=1,stroke = 0,position = position_jitter(width=0.2))+
    facet_grid(.~variable)+
    labs(y="Pseudobulk expression corrected for\nAPOE, Age, and Genomic Ancestry",
         x="Visium Cluster and Sex",
         color="Visium\nCluster",
         fill="Sex")+
    scale_fill_manual(values=sexpal)+
    scale_color_manual(values=pal)+
    theme(strip.background = element_blank(),
          strip.text = element_markdown(size=9,hjust=0.5),
          axis.text.x=element_text(size=8,angle=30,hjust=1,vjust=1))
dev.off()
```

3F: Astro/LC spotplot of HMGCS1 and AQP4 (as reference for astro locations)
v13m06-402_b1s1 (M)
v13m06-331_d1s1 (F)

load spe and annots
```{r}
lc3 <- readRDS("processed-data/06-countsOnly_noImgData_QCed_SPE_split_to_tissSections.RDS")
## calc logcounts on the fly and drop samples not considered for DE

lc3 <- lc3[,!(lc3$brnum %in% paste0("Br",c(5517,5276,5712)))]
lc3 <- computeLibraryFactors(lc3)
lc3 <- logNormCounts(lc3)

# labels
louvs <- readRDS("processed-data/07_featureSelection_dimred_harmony_clustering/04-Initial_louvLeid_res0.5-1-2_clusterings.RDS")
louvs <- louvs$HARMONYlmbna_HDG_SVG_2575[,.(rn,snnHARMONYlmbna_HDG_SVG_2575_louv_res1)]
setnames(louvs,2,"clusid")
anno <- fread("processed-data/08_validitycheck_25hdg75svg_louv1/10-25hdg75svg_louv1_annots.txt")
louvs <- merge.data.table(louvs,anno,by="clusid")

colLabels(lc3) <- DataFrame(louvs,row.names=louvs$rn)[colnames(lc3),"plot_anno"]
rm(louvs,anno)
```

3F continued: eschers
```{r}
rownames(lc3) <- rowData(lc3)$gene_name
plotg <- c("HMGCS1","AQP4")

samps <- lapply(c("V13M06-402_B1s1","V13M06-331_D1s1"),FUN=function(x){
    subspe <- lc3[plotg,lc3$sample_id==x & lc3$label %in% c("LC","Astro")]
    return(subspe)
})

names(samps) <- c("V13M06-402_B1s1 (M)","V13M06-331_D1s1 (F)")

### plots

lapply(plotg,FUN=function(g){
    ## get one legend to use for all plots
    tmpdat <- as.data.table(cbind(as.data.frame(t(as.matrix(logcounts(lc3[g,lc3$label %in% c("LC","Astro")])))),
                                  spatialCoords(lc3[,lc3$label %in% c("LC","Astro")]),
                                  lc3[g,lc3$label %in% c("LC","Astro")]$label))
    setnames(tmpdat,c(1,4),c("lct","lab"))
    
    lctmax <- max(tmpdat$lct)
    
    tmpplt <- ggplot(tmpdat,aes(x=pxl_col_in_fullres,y=pxl_row_in_fullres,fill=lct,col=lab))+
        geom_point()+
        scale_fill_gradient(low="#cecece",high="#000000",limits=c(0,lctmax),na.value = "#FFFFFF")+
        scale_color_manual(values=pal)+
        guides(color="none")+
        labs(fill=paste0("log counts<br>*",g,"*"))+
        theme(legend.title=element_markdown(size=8))
    
    leg.plt <- extract_legend(tmpplt)
    dev.off()
    
    ## now make the eschers without legends
    plt <- mapply(s=samps,n=names(samps),lmx=lctmax,SIMPLIFY =FALSE,FUN=function(s,n,lmn,lmx){
        colData(s)$lct <- as.matrix(logcounts(s[g,]))
        
        s$lct[s$lct==min(s$lct)] <- NA # so that our palette starts in a discernible gray range for expressing spots
        
        sp <- make_escheR(s)
        sp <- sp |> add_ground(var = "label",stroke=0.3,point_size = 0.95)
        sp <- sp |> add_fill(var = "lct",point_size = 0.95)
        
        sp <- sp +
            scale_fill_gradient(low="#cecece",high="#000000",limits=c(0,lctmax),na.value = "#FFFFFF")+
            scale_color_manual(values=pal) +
            guides(color="none",fill="none") +
            ggtitle(n)+
            theme(title=element_text(size=7))
        
        sp <- rasterize(sp,layers="Points",dpi=300,dev="cairo_png")
        return(sp)
    })
    
    ## save
    pdf(paste0("plots/manuscript/Fig4/4F-",g,".pdf"),height=2,width=4.5,onefile = FALSE)
    do.call("grid.arrange",list(arrangeGrob(grobs = plt,ncol = 2),leg.plt,ncol=2,widths=c(3.75,0.75)))
    dev.off()
})
```



