---
title: "00-Make_mainfig_samples_SPE"
format: html
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(SpatialExperiment)
library(data.table)
```

## since there's a lot of image data in the full SPE and we're only going to plot a handful of samples with the images (for main figs), make an SPE subsetted to the samples of interest.

## Additionally, because we will be plotting over the H&E, we want to load the SPE that preceded splitting apart the tissue sections within each capture area.
```{r}
spe <- readRDS("processed-data/04_QC/04-lffLC_noEdges_noLocOutliers_remainder1pctileUMIorGene-removed.RDS")

## append metadata columns we may need later: YRI, NM metrics, hemisphere. almost all of these are in our tsv of the colData for section-level (with a column we can use to join back to capture-level)
tmpcd <- fread("processed-data/06-QCed_SPE_splitToTissSect_colData.txt")
tmpcd <- tmpcd[,.(capture_id,brnum,section,hemisphere,N_NMbodies,Prop_NM,Intensity_NM,CentroidSignalCount_NM,tissueNMscore)]

globanc <- fread("raw-data/ancestryAndHaplotypes/FLARE/global_ancestry_estimates.txt")
globanc[ID=="Br6119",ID:="Br6119(re-dis)"] ## for consistency with other files

tmpcd <- merge.data.table(tmpcd,globanc,by.x="brnum",by.y="ID",all.x=T)
## make sure we have the same number of spots in the capture-level SPE and metadata from after the split
stopifnot(nrow(tmpcd)==ncol(spe))


```