---
title: "01-Minimalist Harmony, bayesspace, and marker extraction"
author: "Bernard Mulvey"
date: "2024-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
library(BiocParallel)
library(harmony)
library(magrittr)
library(scran)
library(scater)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


get lognorm counts, 10%ile HVGs, and run PCA (let SpatialPreprocess do this since that seemed to work with BS 1.14.0) -> HARMONY -> BayesSpace -> get markers
```{r}
lc2 <- readRDS("local_ref/eda_lc_spe_nomitofilt_200umi-130gene_nonLCsampsdropped_051224.RDS")

lc2.vars <- modelGeneVar(lc2)
lc2.vars.fit <- metadata(lc2.vars)

lc2.hvg10 <- scran::getTopHVGs(lc2.vars,prop = 0.1)

set.seed(42)
lc2 <- scater::runPCA(lc2,subset_row=lc2.hvg10)

# remove 10x dimensionality reductions
reducedDims(lc2)$`10x_pca` <- NULL
reducedDims(lc2)$`10x_umap` <- NULL
reducedDimNames(lc2)[1] <- "other10xcrap"
reducedDims(lc2)$other10xcrap <- NULL

### run a minimalist harmony correction
set.seed(42)
lc2 <- harmony:::RunHarmony.SingleCellExperiment(object=lc2,lambda=NULL,group.by.vars = "sample_id",max_iter=100,ncores=4)

rm(lc2.vars,lc2.vars.fit)
gc(full=T)
```

quickcluster
```{r}
set.seed(42)
quickcl <- quickCluster(lc2,BPPARAM=multicoreParam(6))
quickcl2 <- paste0("X",quickcl)
colLabels(lc2) <- quickcl2

tmpout <- as.data.table(colData(lc2),keep.rownames=T)[,.(rn,label)]
fwrite(tmpout,file="processed-data/04-EDA/0-preliminary subset/02-clustering and markers/01-hvg10_harmony_quickcluster_051324.txt",sep="\t",col.names=T,row.names=F)
rm(quickcl)

# save RDS with dimreds
saveRDS(lc2,"local_ref/eda_lc_spe_nomitofilt_200umi-130gene_nonLCsampsdropped_051224.RDS")
gc(full=T)
```
