---
title: "SF-AncAPO_shared_E4downreg_GOcilia_genes_spotplots"
author: "Bernie Mulvey"
date: "07-16-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
library(biomaRt)
library(stringr)
library(escheR)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##


## >= and <= comparators that account for floating point error
greaterOrEqual <- function(x,y) {
    precision <- sqrt(.Machine$double.eps)
    (x >= y) | (abs(x-y) <= precision)
}

lessOrEqual <- function(x,y){
    precision <- sqrt(.Machine$double.eps)
    (x <= y) | (abs(x-y) <= precision)
}

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 8,color = "#000000"), axis.title.x = element_text(size = 9,color = "#000000"), axis.text.y = element_text(size = 8,color = "#000000"), axis.title.y = element_text(size =9,color = "#000000"), plot.title = element_markdown(size = 10,hjust=0.5,color = "#000000"), strip.text = element_text(size=11), legend.text = element_text(size=7,color = "#000000"), legend.title = element_text(size=8,hjust=0.5,color = "#000000"),axis.ticks = element_line(linewidth=0.5),panel.grid.major = element_line(linewidth=0.5),panel.grid.minor=element_line(linewidth=0.25),plot.title.position="plot"))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```


load spe and annots
```{r}
lc3 <- readRDS("processed-data/06-countsOnly_noImgData_QCed_SPE_split_to_tissSections.RDS")
## calc logcounts on the fly and drop samples not considered for DE

lc3 <- lc3[,!(lc3$brnum %in% paste0("Br",c(5517,5276,5712)))]
lc3 <- scater::computeLibraryFactors(lc3)
lc3 <- scater::logNormCounts(lc3)

# labels
louvs <- readRDS("processed-data/07_featureSelection_dimred_harmony_clustering/04-Initial_louvLeid_res0.5-1-2_clusterings.RDS")
louvs <- louvs$HARMONYlmbna_HDG_SVG_2575[,.(rn,snnHARMONYlmbna_HDG_SVG_2575_louv_res1)]
setnames(louvs,2,"clusid")
anno <- fread("processed-data/08_validitycheck_25hdg75svg_louv1/10-25hdg75svg_louv1_annots.txt")
louvs <- merge.data.table(louvs,anno,by="clusid")

colLabels(lc3) <- DataFrame(louvs,row.names=louvs$rn)[colnames(lc3),"plot_anno"]
rm(louvs,anno)
```


## get ancest shared Astro domain E4 downreg genes and subset the term genes to those in the downregs
```{r}
deres <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/02b-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAnces_LabAncesE4E2_noMixClusts_YRIcontAndCat_JUL2025.RDS")

ancstrat <- deres$cat_ances$E2E4label$detabs

aa <- deres$cat_ances$YRIAPOlabel$detabs
ea <- aa[grep(names(aa),pattern="E4CEU_vs_E2CEU",value=T)]
aa <- aa[grep(names(aa),pattern="E4YRI_vs_E2YRI",value=T)]


ea.ast <- ea$Astro_E4CEU_vs_E2CEU
aa.ast <- aa$Astro_E4YRI_vs_E2YRI

setnames(ea.ast,c("logFC","adj.P.Val"),c("logFC.EA","FDR.EA"))
setnames(aa.ast,c("logFC","adj.P.Val"),c("logFC.AA","FDR.AA"))

shareg <- merge.data.table(ea.ast[lessOrEqual(FDR.EA,0.05),.(gene_id,gene_name,logFC.EA,FDR.EA)],aa.ast[lessOrEqual(FDR.AA,0.05),.(gene_id,gene_name,logFC.AA,FDR.AA)],by=c("gene_id","gene_name"))
shareg[,signmatch:=ifelse(greaterOrEqual(logFC.EA*logFC.AA,0),1,0)]
shareg <- shareg[signmatch==1]

### we need to be sure we have entrez symbols for enrichr gene matching
biomart <- useMart(biomart = "ENSEMBL_MART_ENSEMBL",dataset="hsapiens_gene_ensembl")
lut <- biomaRt::getBM(attributes=c("ensembl_gene_id",
                                   "entrezgene_id",
                                   "entrezgene_accession",
                                   "entrezgene_description"),
                      mart=biomart,
                      filter="ensembl_gene_id",
                      values=shareg$gene_id) # uh ok "accession" = symbol

lut <- as.data.table(lut)
dropg <- lut[,.N,by="entrezgene_accession"][N>1,entrezgene_accession]
lut <- lut[!(entrezgene_accession %in% dropg)]
lut <- lut[!is.na(entrezgene_accession)]
## our background list (all genes tested for DE) which was used to make this lookup table should be updated to reflect genes where the symbols are not duplicated. make sure there's only one row per accession-id now:
stopifnot(length(unique(lut$entrezgene_accession))==nrow(lut))

## merge shareg with the filterd lut, so only keeping genes with unique symbols after merge
shareg <- merge.data.table(shareg,lut[,.(ensembl_gene_id,entrezgene_accession)],by.x="gene_id",by.y="ensembl_gene_id") # 110 of 113 retained

rm(lut,dropg,ea,ea.ast,aa.ast,deres,ancctrl,biomart,aa)
gc()
```


### get genes from top cilia terms; also, write out a sup tab of nominally significant enrichr hits for ancestry-shared E4-E2 DEGs.
```{r}
enrichrg <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/14-AncestryShared_Astro_E4E2DEGs_Enrichr.RDS")

## min 3 gene overlap, nominal p 0.05
enrichrg.supt <- enrichrg[lessOrEqual(P.value,0.05)&greaterOrEqual(N_genes,3)]
fwrite(enrichrg.supt,"plots/manuscript/SuppTabs/Ancest_Shared_AstroDEGs_nomEnrichrs.txt",sep='\t',quote=F,row.names=F,col.names=T)

enrichrg <- enrichrg[N_genes>15&Adjusted.P.value<0.05]
enrichrg <- enrichrg[predomAncestWiseE4vsE2=="sharedown"]
enrichrg <- enrichrg[!(Term %in% grep(Term,pattern="ARCHS4",value=T))]


## get the E4-down DEGs that are in the cilium term
cilg <- str_split_fixed(enrichrg[Term=="Cilium (GO:0005929)",Genes],pattern = ";",n=Inf)
cilg <- cilg[cilg %in% shareg[lessOrEqual(logFC.EA,0)&signmatch==1,entrezgene_accession]] ## 22 genes, damn!
cilgid <- rowData(lc3)[which(rowData(lc3)$gene_id %in% shareg[entrezgene_accession %in% cilg,gene_id]),"gene_id"]

## subset to Astro domain, score each spot, use distributions to determine global minimum for qualifying and identify some top %ile score within sample that falls above it
## subset to domains and cilia genes of interest
lcil <- lc3[cilgid,]

## use spatialLIBD internal function for getting a multigene Z score
ctmat.t <- t(counts(lcil))
zscr <- spatialLIBD:::multi_gene_z_score(ctmat.t)
zscr <- DataFrame(as.matrix(zscr))
colData(lcil)$GOcilia_hits_Zscr <- zscr[colnames(lcil),]
```
 


## define helper function to extract a single legend - from https://statisticsglobe.com/add-common-legend-to-combined-ggplot2-plots-in-r/#example-2-add-shared-legend-to-ggplot2-plots-using-gridextra-package 
```{r}
extract_legend <- function(my_ggp) {
  step1 <- ggplot_gtable(ggplot_build(my_ggp))
  step2 <- which(sapply(step1$grobs, function(x) x$name) == "guide-box")
  step3 <- step1$grobs[[step2]]
  return(step3)
}
```



## escheR plots: samples
V13M06-333_C1s1
V13M06-333_B1s2
V13M06-404_B1s2
V13M06-332_D1s1

```{r}
lcil$APOE <- ifelse(lcil$APOE %in% grep(lcil$APOE,pattern="E4",value=T),"E4","E2")
lcil$ancapo <- paste0(lcil$Ancestry," ",lcil$APOE)
lcil$alph <- ifelse(lcil$label=="Astro","Astro","other")

pltsamps <- c("V13M06-333_C1s1","V13B23-286_A1s1","V13M06-404_B1s2","V13M06-332_D1s1")

## get the global z-score range for the dataset to make the legend

minz <- min(lcil$GOcilia_hits_Zscr)
maxz <- max(lcil$GOcilia_hits_Zscr)

## get a legend
tmpcd <- as.data.table(colData(lcil),keep.rownames=T)[,.(Sex,GOcilia_hits_Zscr,rn,ancapo)]
legplt <- ggplot(tmpcd,aes(x=Sex,y=GOcilia_hits_Zscr,fill=GOcilia_hits_Zscr))+geom_point()+scale_fill_viridis_c(limits=c(minz,maxz),begin=0.15)+labs(fill="Mean Z scored\nexpression: 22 genes\nE4-down in Astro\nDomain of both\nAncestries\nand in GO 'Cilia'")+theme(legend.title=element_text(size=7))
leg <- extract_legend(legplt)
dev.off()

alphs <- c(1,0.45)
names(alphs) <- c("Astro","other")

plts <- lapply(pltsamps,function(x){
    # pltset <- lapply(x,function(y){
        # curdat <- lcil[,lcil$sample_id==y]
        curdat <- lcil[,lcil$sample_id==x]
        
        eschy <- make_escheR(curdat)
        eschy <- add_fill(eschy,var="GOcilia_hits_Zscr",point_size=2.125)+
            aes(alpha=alph)+scale_alpha_manual(values=alphs)
        eschy <- eschy+ggtitle(paste0(unique(curdat$brnum),",",unique(curdat$ancapo)))
        eschy <- eschy+guides(fill="none",alpha="none")+
            theme(title=element_text(size=10,hjust=0.5,vjust=0.5))
        eschy <- eschy+scale_fill_viridis_c(limits=c(minz,maxz),begin=0.15)
        return(eschy)
    # })
    # return(pltset)
})

png("plots/manuscript/SuppFigs/SF-CrossAncesE4down_CiliaGeneZscores.png",width=9.5,height=6,units="in",res=300)
do.call("grid.arrange",list(arrangeGrob(grobs=plts,nrow=2),leg,ncol=2,widths=c(8,1.5)))
dev.off()
```