---
title: "01-Minimalist Harmony, bayesspace, and marker extraction"
author: "Bernard Mulvey"
date: "2023-10-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
knitr::opts_chunk$set(fig.width=7,fig.height=10)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(Biostrings)
library(ggplot2)
library(gridExtra)
library(SpatialExperiment)
library(spatialLIBD)
require(colorout)
source("~/.R/calc_tau_for_cellOrTissueSpecificity_metric.R")
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")

## change write.table to output a TSV without quotes or rownames by default
library(default)
default(write.table) <- list(row.names=F,col.names=T,sep='\t',quote=F)

theme_set(theme_bw()+theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16), axis.text.y = element_text(size = 14), axis.title.y = element_text(size =16), plot.title = element_text(size = 20,hjust=0.5), strip.text = element_text(size=18), legend.text = element_text(size=10), legend.title = element_text(size=11,hjust=0.5)))
```


get HVGs and run a minimalist PCA -> HARMONY -> quickcluster -> get markers
```{r}
lc2 <- readRDS("processed-data/04-EDA/0-preliminary subset/lc_spe_nomitofilt_200umi-130gene_nonLCsampsdropped_102923.RDS")

lc2.vars <- modelGeneVar(lc2)
lc2.vars.fit <- metadata(lc2.vars)

lc2.hvg10 <- scran::getTopHVGs(lc2.vars,prop = 0.1)

set.seed(42)
lc2 <- scater::runPCA(lc2,subset_row=lc2.hvg10)
### run a minimalist harmony correction
set.seed(42)
lc2 <- harmony::RunHarmony(lcpca,group.by.vars = "sample_id")

rm(lc2.vars,lc2.vars.fit)
gc(full=T)
```

#### BayesSpace: q=10 (arbitrary), 7.5k iter
```{r}
library(BayesSpace)

colData(lc2)$row <- colData(lc2)$array_row
colData(lc2)$col <- colData(lc2)$array_col
lc2bs <- spatialPreprocess(lc2,platform = "Visium",skip.PCA = T)

# forgot to set seed! doh
# set.seed(42)
tmp <- BayesSpace::spatialCluster(sce = lc2bs,q = 10,use.dimred="HARMONY",d = 50,platform = "Visium",nrep = 7500,init.method = "mclust")

bsq10.i7500 <- as.data.table(colData(tmp),keep.rownames=T)[,.(rn,cluster.init,spatial.cluster)]
# fwrite(bsq10.i7500,"processed-data/04-EDA/0-preliminary subset/02-clustering and markers/01-hvg10_harmony_BS_k10_7500iter.txt",sep='\t',quote=F)
```

### examine the BS clusters
```{r}
bsq10.i7500 <- DataFrame(bsq10.i7500)
rownames(bsq10.i7500) <- bsq10.i7500$rn
bsq10.i7500 <- bsq10.i7500[colnames(lc2),]
#bsq10.i7500$spatial.cluster <- paste0("X",bsq10.i7500$spatial.cluster)

colLabels(lc2) <- factor(bsq10.i7500[,3])
library(Polychrome)
pal <- Polychrome::palette36.colors(n = 18)[c(2:9,15,18)]
# next line is needed for consistency in color-cluster assignments between libdspatial and the generated legend below
names(pal) <- c(1:length(unique(lc2$label)))

plt <- vis_grid_clus(lc2,"label",pdf_file = NULL,return_plots = T,spatial=F,point_size = 2,auto_crop = T,sort_clust = F,colors = pal)
plt <- lapply(plt,FUN=function(x){
    y <-x+
        guides(colour = guide_legend(override.aes = list(size=6)))+
        theme(axis.title = element_blank(),axis.text = element_blank(),legend.title = element_text(size=16),legend.text=element_text(size=15),plot.title = element_text(size=14,hjust=0.5),strip.text=element_text(size=11),plot.subtitle = element_text(size=11))
    return(y)
})

library(gridExtra)
do.call("grid.arrange",plt)
dev.off()
```

Get markers
```{r}
library(dreamlet)
library(BiocParallel)
sbp <- MulticoreParam(10)
register(sbp)
pb <- dreamlet::aggregateToPseudoBulk(lc2,assay = "counts",sample_id = "sample_id",cluster_id = "label",BPPARAM = sbp)
typespec <- dreamlet::cellTypeSpecificity(pb)

lc2$label <- paste0("X",lc2$label)
lc2$label <- factor(lc2$label)
slibdmk <- spatialLIBD::registration_wrapper(lc2,"label","sample_id",gene_ensembl = "gene_id",gene_name = "gene_name",min_ncells = 8)

slibdmks <- slibdmk[["enrichment"]]
```
