---
title: "ST-DEandDE-GSEA"
author: "Bernie Mulvey"
date: "2025-09-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
# library(SpatialFeatureExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
#

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

DE result tables: Sex, E4vE2, AAvEA
```{r}
deres <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/02b-voomLmFit_objs_and_DE_tables_LabSex_LabE2vE4_LabSingleGenos_LabAnces_LabAncesE4E2_noMixClusts_YRIcontAndCat_JUL2025.RDS")

## grab the easy ones first, where there's only one contrast per label. sex and E4-E2 are using continuous ancestry; the ancestry DE uses predominant ancestry.
derestabs <- list(Sex=deres$cont_ances$sexlabel$detabs,
                  E4vE2=deres$cont_ances$E2E4label$detabs,
                  YRI=deres$cat_ances$AncesByLabel$detabs)

derestabs <- mapply(X=derestabs,Y=names(derestabs),SIMPLIFY = FALSE,function(X,Y){
    z <- rbindlist(X,idcol="Domain")
    pat <- paste0("^(.*)_",Y,"$")
    z[,Domain:=gsub(Domain,pattern=pat,replacement="\\1")]
    setnames(z,"t","t statistic")
    z <- z[,.(Domain, gene_name, logFC, P.Value, adj.P.Val, `t statistic`, gene_id, chr)]
    return(z)
})

names(derestabs)[3] <- "AAvEA"
mapply(x=derestabs,n=names(derestabs),SIMPLIFY=FALSE,function(x,n){
    fwrite(x,paste0("plots/manuscript/SuppTabs/TabDelims/DEtabs/DEresults_",n,".txt"),sep='\t',quote=F,row.names=F,col.names=T)
})

rm(derestabs)
```

Additional DE analyses: predomAncestry-APOE subgroups (categorical ancestry); APOE genotype subgroups (continuous ancestry)
```{r}
apocomps <- grep(names(deres$cont_ances$ApoAllelesLabel$detabs),pattern="^LC.*$",value=T)
apocomps <- gsub(apocomps,pattern="LC_",replacement="")

derestabs <- lapply(apocomps,function(a){
    getnames <- grep(names(deres$cont_ances$ApoAllelesLabel$detabs),pattern=a,value=T)
    z <- rbindlist(deres$cont_ances$ApoAllelesLabel$detabs[getnames],idcol="Domain")
    pat <- paste0("^(.*)_",a,"$")
    z[,Domain:=gsub(Domain,pattern=pat,replacement="\\1")]
    setnames(z,"t","t statistic")
    z <- z[,.(Domain, gene_name, logFC, P.Value, adj.P.Val, `t statistic`, gene_id, chr)]
    return(z)
})
names(derestabs) <- apocomps
mapply(x=derestabs,n=names(derestabs),SIMPLIFY=FALSE,function(x,n){
    fwrite(x,paste0("plots/manuscript/SuppTabs/TabDelims/DEtabs/DEresults_",n,".txt"),sep='\t',quote=F,row.names=F,col.names=T)
})

rm(derestabs)

## now the categorical ancestry DEs, stratified by APOE genotype
ancescomps <- grep(names(deres$cat_ances$YRIAPOlabel$detabs),pattern="^LC.*$",value=T)
ancescomps <- gsub(ancescomps,pattern="^LC_",replacement="")
derestabs <- lapply(ancescomps,function(a){
    getnames <- grep(names(deres$cat_ances$YRIAPOlabel$detabs),pattern=a,value=T)
    z <- rbindlist(deres$cat_ances$YRIAPOlabel$detabs[getnames],idcol="Domain")
    pat <- paste0("^(.*)_",a,"$")
    z[,Domain:=gsub(Domain,pattern=pat,replacement="\\1")]
    setnames(z,"t","t statistic")
    z <- z[,.(Domain, gene_name, logFC, P.Value, adj.P.Val, `t statistic`, gene_id, chr)]
    return(z)
})

names(derestabs) <- ancescomps

mapply(x=derestabs,n=names(derestabs),SIMPLIFY=FALSE,function(x,n){
    fwrite(x,paste0("plots/manuscript/SuppTabs/TabDelims/DEtabs/DEresults_",n,".txt"),sep='\t',quote=F,row.names=F,col.names=T)
})
```
