---
title: "SupTab-Demos_and_seq_metrics"
author: "Bernie Mulvey"
date: "2025-07-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

## read in the colData and QC tables
```{r}
cddt <- fread("processed-data/06-QCed_SPE_splitToTissSect_colData.txt")
qcres <- fread("processed-data/04_QC/04-Samplewise UMI and gene stats per filt step.txt")

cddt <- cddt[,.(sample_id,capture_id,APOE,Ancestry,Sex,Age,Rin,Visium_slide,brnum,Kit,hemisphere,tissueNMscore)]

cddt <- unique(cddt)
cddt <- merge.data.table(cddt,qcres[filtstep=="BotPtile_UMIorGene_removal",],by.x="capture_id",by.y="sample_id")
cddt[,filtstep:=NULL]

## note which samples were excluded from DE analyses
cddt[,inDEanalyses:="Yes"]
cddt[brnum %in% paste0("Br",c(5517,5276,5712)),inDEanalyses:="No"]
cddt[brnum=="Br6119(re-dis)",brnum:="Br6119"]

ntiss <- cddt[,.(capture_id,sample_id)][,.N,by="capture_id"]
setnames(ntiss,"N","num_tissue_sections")
cddt <- merge.data.table(cddt,ntiss,by="capture_id")
cddt[,sample_id:=NULL]
cddt <- unique(cddt)
cddt[,meanTissueNMscores:=mean(tissueNMscore,na.rm=T),by="capture_id"]
cddt[,tissueNMscore:=NULL]
cddt <- unique(cddt)

setnames(cddt,"Ancestry","Predominant Genomic Ancestry")
cddt[`Predominant Genomic Ancestry`=="EA",`Predominant Genomic Ancestry`:="CEU"]
cddt[`Predominant Genomic Ancestry`=="AA",`Predominant Genomic Ancestry`:="YRI"]

setnames(cddt,"Rin","Cortical_Tissue_Rin")

fwrite(cddt,"plots/manuscript/SuppTabs/SupTab-Demos_and_seq_metrics_colData.txt",sep="\t",quote=FALSE,row.names=FALSE)
```
