---
title: "SupTabs-Fig3Related"
author: "Bernie Mulvey"
date: "2025-09-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(ggplot2)
library(ggtext)
library(gridExtra)
# library(SpatialFeatureExperiment)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")


## ggplot defaults
theme_set(theme_bw()+theme(axis.text.x = element_text(size = 8,color = "#000000"), axis.title.x = element_text(size = 9,color = "#000000"), axis.text.y = element_text(size = 8,color = "#000000"), axis.title.y = element_text(size =9,color = "#000000"), plot.title = element_markdown(size = 10,hjust=0.5,color = "#000000"), strip.text = element_text(size=11), legend.text = element_text(size=7,color = "#000000"), legend.title = element_text(size=8,hjust=0.5,color = "#000000"),axis.ticks = element_line(linewidth=0.5),panel.grid.major = element_line(linewidth=0.5),panel.grid.minor=element_line(linewidth=0.25),plot.title.position="plot"))

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

# intra-LC nnSVG results
```{r}
lcnnsvg <- fread("processed-data/09_local_svgs/01d-LC prelim nnSVG 5addnl recovered samples nomsig genes and ranks per sample.txt")

names(lcnnsvg)
reordn <- c("gene_id","gene_name","nsigsamps","meanrank")
reordn <- c(reordn,names(lcnnsvg)[!(names(lcnnsvg) %in% reordn)])

lcnnsvg <- lcnnsvg[,..reordn]
fwrite(lcnnsvg,"plots/manuscript/SuppTabs/TabDelims/LCsvg_results.txt",sep='\t',quote=F,row.names=F,col.names=T)
rm(lcnnsvg,reordn)
```

LC NM+ vs NM- DE results
```{r}
nmde <- fread("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/04-LCNMpos_vs_LCNMneg_DE.txt")

names(nmde)
reordn <- c("gene_name","logFC","P.Value","adj.P.Val","t","B","gene_id","chr")
nmde <- nmde[,..reordn]
fwrite(nmde,"plots/manuscript/SuppTabs/TabDelims/LCNMpos_vs_LCNMneg_DE.txt",sep='\t',quote=F,row.names=F,col.names=T)
rm(nmde,reordn)
```

NM DE GSEA
```{r}
nmgsea <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/05-LCNMposVsNeg_msigdb_and_tftarg_GSEAs.RDS")

## extract TF symbols from the TF-Targ set names
y <- nmgsea[[2]][!(pathway %in% grep(pathway,pattern="Rummagene",value=T))]
y[,tf:=apply(.SD,MARGIN = 1,FUN=function(h){strsplit(h,"_",1)[[1]][1]}),.SDcols="pathway"]
### rummagene TFs are named differently:
z <- nmgsea[[2]][pathway %in% grep(pathway,pattern="Rummagene",value=T)]
# reverse the output of a strsplit of a strsplit o.0 to get the string immediately preceding "_Rummagene_.."
z[,tf:=apply(.SD,MARGIN=1,FUN=function(p){
    rev.default(strsplit(
        strsplit(p,"_Rummagene_transcription_factors",-1)[[1]][1],
        "_")[[1]]
    )[1]
}),.SDcols="pathway"]
#z[,tf:=gsub(pathway,pattern=".*-.*_(.*)_Rummagene_transcription_factors)",replacement="\\1")]
fix <- rbind(z,y)
# make all upper case
fix[,tf:=toupper(tf)]
nmgsea[[2]] <- fix


## concat and save
nmgsea <- rbindlist(nmgsea,idcol="params",fill=T)

nmgsea[,`Geneset Source`:=gsub(params,pattern="^(.*)_.*$",replacement="\\1")]
nmgsea[,signed:=gsub(params,pattern="^.*_(.*)$",replacement="\\1")]
nmgsea[,signed:=ifelse(signed=="signed","Yes","No")]
setnames(nmgsea,"signed","Directed Test")
nmgsea[,params:=NULL]

reordn <- c("Geneset Source","Directed Test","tf","pathway","dir","pval","padj","NES","ES","leadingEdge","size","log2err")
nmgsea <- nmgsea[,..reordn]
fwrite(nmgsea,"plots/manuscript/SuppTabs/TabDelims/LCNMpos_vs_LCNMneg_DE_GSEA.txt",sep='\t',quote=F,row.names=F,col.names=T)

rm(nmgsea,reordn)
```

NMF factor-gene sets; full NMF matrix for supp data
```{r}
nmfmat <- readRDS("processed-data/10_subclustering/07b-lcnmf160_tol1e-9_rowSumLogctFilt18.RDS") # okay that can just be copied over as is
rm(nmfmat)

filt <- fread("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/06b-LCNMFLogCt18Filt_factors_and_factorSpecGenes_min25specGenes.txt")

filt <- filt[,.(gene_id,gene_name,factor,value,medianloading)]
setnames(filt,"value","Gene Weight")
setnames(filt,"medianloading","Median Factor Loading")
setnames(filt,"factor","NMF Factor(s) Specific to Gene")
fwrite(filt,"plots/manuscript/SuppTabs/TabDelims/LCNMF_prefiltct_factorspecificgenes.txt",sep='\t',quote=F,row.names=F,col.names=T)
rm(filt,nmfmat)
```

NMF factor-gene set enrichr results (FDR-sig only)
```{r}
nmfg <- readRDS("processed-data/10_subclustering/09-LCnmfFilt_factorSpecGenes_enrichr_results.RDS")

nmfg <- nmfg[Adjusted.P.value<0.05]
fwrite(nmfg,"plots/manuscript/SuppTabs/NMF_factorspecificgene_Enrichr_FDR05.txt",sep='\t',quote=F,row.names=F,col.names=T)
rm(nmfg)
```

SCORPION GRN edge comparisons
```{r}
scorp <- readRDS("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/12e2-Pbulkprefilt_LCNMposNeg_GRNs_NMdomainSpecEdge_or_SpecEdgeandSpecTF_filt.RDS")

specedge <- scorp$pbulkfilt_rnet_specEdgesOnly
specedgeortf <- scorp$pbulkfilt_rnet_specEdge_or_EdgeWith80pctSpecTF

##
specedge[,nmp_pn:=NULL]
specedge[,nmn_pn:=NULL]
specedge[,Specificity:=ifelse(nmp_spec=="Y",yes="NM+",no=ifelse(nmn_spec=="Y",yes="NM-","Non-specific"))]
specedge[,nmp_spec:=NULL]
specedge[,nmn_spec:=NULL]

fwrite(specedge,"plots/manuscript/SuppTabs/TabDelims/LCNM_GRN_1700specificedges.txt",sep='\t',quote=F,row.names=F,col.names=T)
rm(specedge)
##
##
specedgeortf[,nmp_pn:=NULL]
specedgeortf[,nmn_pn:=NULL]
specedgeortf[,Specificity:=ifelse(nmp_spec=="Y",yes="NM+",no=ifelse(nmn_spec=="Y",yes="NM-","Non-specific"))]
specedgeortf[,nmp_spec:=NULL]
specedgeortf[,nmn_spec:=NULL]

fwrite(specedgeortf,"plots/manuscript/SuppTabs/TabDelims/LCNM_GRN_specEdge_orEdgeWspecificTF.txt",sep='\t',quote=F,row.names=F,col.names=T)
##

spectf <- fread("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/12h1-TFs_withOver80Pct_NMpos_spec_edges_inPbulkPrefiltGRN.txt",header=F)
spectf[,Specificity:="NM+"]

spectf2 <- fread("processed-data/12_DEanalyses_removedsampsAndFinalNMseg/12h2-TFs_withOver80Pct_NMneg_spec_edges_inPbulkPrefiltGRN.txt",header=F)
spectf2[,Specificity:="NM-"]
spectfs <- rbind(spectf,spectf2)

fwrite(spectfs,"plots/manuscript/SuppTabs/TabDelims/LCNM_GRN_TFs_with80pct_specificedges.txt",sep='\t',quote=F,row.names=F,col.names=T)
```
