---
title: "03-allgeneGLMPCA_louvain_markers"
output: html_document
date: "2024-09-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.height = 10,fig.width = 7,include = FALSE)
#### sets tab autocompletion for directories to begin from the directory containing the .Rproj session, instead of the script's directory if different
knitr::opts_knit$set(root.dir = here::here())

library(data.table)
library(SpatialExperiment)
library(spatialLIBD)
library(HDF5Array)

## rstudio GUI tweaks
require(colorout)
ColorOut()
options("styler.addins_style_transformer" = "biocthis::bioc_style()")
##

## enable forked parallel processing with BiocParallel::multicoreParam, future::, etc. seemed to need this a couple times, but otherwise havent so its here as a preventative measure. part of this is adding the line 
# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
# to Renviron.site. see e.g. top response on https://stackoverflow.com/questions/73638290/python-on-mac-is-it-safe-to-set-objc-disable-initialize-fork-safety-yes-globall 
library(parallelly)
options(parallelly.supportsMulticore.disableOn="")
options(parallelly.fork.enable=TRUE)
library(BiocParallel)
options(bphost="localhost")
library(parallel)

## last of all, unload the base package datasets, whose data keep getting in the way of autocompletions (e.g., Theoph is priortized over TRUE)
unloadNamespace("datasets")
```

### load (louvain) clusterings from SNN k10,15,20 of all gene GLMPCA -> use spatiallibd registration_wrapper for marker detection
```{r}
lc2 <- readRDS("processed-data/05_QC/04-lffLC_noEdges_noLocOutliers_remainder1pctileUMIorGene-removed.RDS")

SNNlouvlist <- readRDS("processed-data/07_Clustering/01-GLMPCAallgene_SNN10-15-20_leidenAndLouvain_res05-1-2.RDS")
SNNlouvlist <- lapply(SNNlouvlist,as.data.table)
snnlouvs <- merge.data.table(SNNlouvlist[[1]],SNNlouvlist[[2]],by="rn")
snnlouvs <- merge.data.table(snnlouvs,SNNlouvlist[[3]],by="rn")

keepclus <- c("rn",grep(names(snnlouvs),pattern="louv",value=T))
snnlouvs <- snnlouvs[,..keepclus]

louvmks <- lapply(keepclus[c(2:length(keepclus))],FUN=function(l){
    tmpcols <- c("rn",l)
    tmplabs <- snnlouvs[,..tmpcols]
    setnames(tmplabs,2,"curclus")
    
    tmplabs <- DataFrame(tmplabs,row.names=tmplabs$rn)[colnames(lc2),]
    
    colLabels(lc2) <- tmplabs$curclus
    
    mks <- registration_wrapper(lc2,var_registration = "label",var_sample_id = "sample_id",gene_ensembl = "gene_id",gene_name = "gene_name")
    
    mks <- as.data.table(mks[["enrichment"]])
    
}












```
